import React from 'react';
import { ArrowLeft } from 'lucide-react';
import { Button } from '../components/shared/Button';

const MOCK_GLOSSARY = [
    { term: 'Epoch', definition: 'One complete pass of the entire training dataset through the network.' },
    { term: 'Weights', definition: 'The learnable parameters that represent the strength of connection between neurons.' },
    { term: 'Bias', definition: 'An additional parameter that shifts the activation function to fit data better.' },
    { term: 'Backpropagation', definition: 'The algorithm used to calculate the gradient of the loss function with respect to weights.' },
    { term: 'Softmax', definition: 'A function that turns numbers into probabilities that sum to one.' }
];

export function NoteDetailScreen({ note, onBack }: { note: any, onBack: () => void }) {
    return (
        <div style={{ display: 'flex', gap: '32px', padding: '0 24px', maxWidth: '1400px', margin: '0 auto' }}>

            {/* Main Content Column */}
            <div style={{ flex: 1, display: 'flex', flexDirection: 'column', gap: '24px' }}>
                <Button variant="ghost" icon={ArrowLeft} onClick={onBack} style={{ width: 'fit-content' }}>
                    Back to Notes
                </Button>

                <article style={{ color: '#FFF' }}>
                    <h2 style={{ fontSize: '12px', color: '#a855f7', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
                        Lecture Material • Module 4
                    </h2>
                    <h1 style={{ fontSize: '36px', fontWeight: 700, margin: '8px 0' }}>{note.title}</h1>

                    <div style={{ color: 'var(--text-secondary)', fontSize: '16px', lineHeight: '1.8', marginTop: '24px' }}>
                        <p>An in-depth exploration of neural network topology, activation functions, and the mathematical framework that enables deep learning. Generated by Pilot AI from the core curriculum datasets.</p>

                        <h3 style={{ color: '#FFF', marginTop: '32px' }}>1. Topological Constraints</h3>
                        <p>Neural networks are structured as acyclic graphs where layers represent stages of feature abstraction. In a standard Multi-Layer Perceptron (MLP), we define three primary layer types:</p>
                        <ul style={{ paddingLeft: '20px', marginBottom: '24px' }}>
                            <li style={{ marginBottom: '8px' }}><strong>Input Layer:</strong> Mapping raw data vectors (x) to the network's latent space.</li>
                            <li style={{ marginBottom: '8px' }}><strong>Hidden Layers:</strong> Non-linear transformations that capture complex relationships.</li>
                            <li style={{ marginBottom: '8px' }}><strong>Output Layer:</strong> Producing the final prediction based on the task.</li>
                        </ul>

                        <h3 style={{ color: '#FFF', marginTop: '32px' }}>2. Activation Mechanisms</h3>
                        <p>Without non-linear activation functions, a neural network is merely a sequence of matrix multiplications, mathematically equivalent to a single linear layer. The ReLU (Rectified Linear Unit) has become the industry standard for hidden layers due to its efficiency in mitigating vanishing gradient problems.</p>

                        <h3 style={{ color: '#FFF', marginTop: '32px' }}>3. Parameter Optimization</h3>
                        <p>During training, the objective is to minimize the loss function. We utilize Stochastic Gradient Descent (SGD) to update weights iteratively. The frequency and magnitude of these updates are controlled by the learning rate, a critical hyperparameter.</p>

                        <h3 style={{ color: '#FFF', marginTop: '32px' }}>4. Scaling and Regularization</h3>
                        <p>To prevent overfitting, we introduce regularization techniques such as Dropout or L2 regularization. This ensures the model generalizes well to unseen data, rather than simply memorizing the training set.</p>
                    </div>
                </article>
            </div>

            {/* Sticky Sidebar */}
            <aside style={{ width: '300px', display: 'flex', flexDirection: 'column', gap: '24px', position: 'sticky', top: '24px', height: 'fit-content' }}>
                <div style={{ backgroundColor: '#181818', border: '1px solid #333', borderRadius: '12px', padding: '20px' }}>
                    <h4 style={{ fontSize: '12px', color: 'var(--text-secondary)', marginBottom: '12px' }}>SOURCE MODULE</h4>
                    <div style={{ fontSize: '14px', fontWeight: 600 }}>Advanced ML Course</div>
                    <div style={{ fontSize: '12px', color: 'var(--text-muted)', marginTop: '4px' }}>Unit 4: Deep Learning Foundations</div>
                </div>

                <div style={{ backgroundColor: '#181818', border: '1px solid #333', borderRadius: '12px', padding: '20px' }}>
                    <h4 style={{ fontSize: '12px', color: 'var(--text-secondary)', marginBottom: '16px' }}>KEY TERMS GLOSSARY</h4>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
                        {MOCK_GLOSSARY.map((item, idx) => (
                            <div key={idx}>
                                <div style={{ fontSize: '13px', fontWeight: 600, color: '#FFF' }}>{item.term}</div>
                                <div style={{ fontSize: '12px', color: 'var(--text-secondary)', marginTop: '4px' }}>{item.definition}</div>
                            </div>
                        ))}
                    </div>
                </div>
            </aside>
        </div>
    );
}